/**
 * MLTD 相关常量定义
 */

export const ANNIVERSARY_CONSTANTS = {
  STAMINA_COST_GAIN_TOKEN: 450,
  TOKENS_PER_GAIN_PLAY: 1071,

  TOKENS_PER_BURN_PLAY: 720,
  PT_PER_BURN_PLAY: 2148,
  get TOKEN_TO_PT_RATIO() {
    return this.PT_PER_BURN_PLAY / this.TOKENS_PER_BURN_PLAY;
  },

  STAMINA_COST_PER_BOOST: 4500,
  BOOST_PLAYS_PER_FIRE: 10,
  TOKENS_PER_BOOST_PLAY: 1071 * 2,

  DAILY_LOGIN_TOKENS: 540,
  DAILY_FIRST_SONG_TOKENS: 4000,
  get DAILY_FREE_TOKENS() {
    return this.DAILY_LOGIN_TOKENS + this.DAILY_FIRST_SONG_TOKENS;
  },

  STAMINA_RECOVER_PER_DAY: 24 * 12,

  DAILY_MAX_STAMINA_BONUS_COUNT: 2,
  DAILY_STAMINA_30_COUNT: 10,

  JEWEL_PER_FULL_STAMINA: 50,

  EVENT_TOTAL_DAYS: 13,
  EVENT_TOTAL_BOOSTS: 13,

  MAX_TARGET_PT: 99999999,
  MAX_LEVEL: 999,
  MAX_TOKENS: 9999999,
  MAX_STAMINA_BOTTLES: 9999,
  MAX_TIME_MINUTES: 30,
} as const;
